/**
 * @canadian-plans/contracts — Zod request/response schemas, the canonical error
 * envelope, the OpenAPI generator, and the one typed API client consumed by
 * both admin and the storefronts. No provider secrets or SDK clients. Browser-
 * safe CMS schema definitions land under an explicit `cms` export in a later
 * task.
 */

// Shared scalars, error-envelope pieces, versioned form helper
export {
  countryCodeSchema,
  currencyCodeSchema,
  domainErrorCodeSchema,
  emailSchema,
  errorDetailsSchema,
  isoDateTimeSchema,
  moneySchema,
  pageInfoSchema,
  requestIdSchema,
  schemaVersionSchema,
  versionedFormSchema,
  type CountryCode,
  type CurrencyCode,
  type DomainErrorCode,
  type Email,
  type ErrorDetails,
  type IsoDateTime,
  type Money,
  type PageInfo,
  type RequestId,
  type SchemaVersion,
  type VersionedForm,
} from './common';

// API-surface vocabularies
export {
  MAX_DOCUMENT_BYTES,
  archiveStateSchema,
  commissionRuleTypeSchema,
  commissionStateSchema,
  deliveryStateSchema,
  documentChecklistKeySchema,
  documentMediaTypeSchema,
  documentParentTypeSchema,
  invoiceStatusSchema,
  orderFulfilmentStatusSchema,
  partnerStatusSchema,
  paymentStateSchema,
  type ArchiveState,
  type CommissionRuleType,
  type CommissionState,
  type DeliveryState,
  type DocumentChecklistKey,
  type DocumentMediaType,
  type DocumentParentType,
  type InvoiceStatus,
  type OrderFulfilmentStatus,
  type PartnerStatus,
  type PaymentState,
} from './domain';

export { healthResponseSchema, type HealthResponse } from './health';

export {
  adminJobSchema,
  adminJobStatusSchema,
  listWorkspaceJobsResponseSchema,
  retryWorkspaceJobResponseSchema,
  type AdminJob,
  type AdminJobStatus,
  type ListWorkspaceJobsResponse,
  type RetryWorkspaceJobResponse,
} from './jobs';

export {
  catalogueOfferStatusSchema,
  catalogueStatusResponseSchema,
  catalogueSyncErrorSchema,
  commercialOfferSchema,
  publishedOfferSchema,
  type CatalogueOfferStatus,
  type CatalogueStatusResponse,
  type CatalogueSyncError,
  type CommercialOffer,
  type PublishedOffer,
} from './catalogue';

export {
  apiErrorCodeSchema,
  apiErrorResponseSchema,
  apiErrorSchema,
  authErrorCodeSchema,
  inviteStaffRequestSchema,
  inviteStaffResponseSchema,
  membershipStatusSchema,
  revokeStaffResponseSchema,
  staffAuthErrorCodeSchema,
  staffPermissionNameSchema,
  staffRoleNameSchema,
  staffWorkspaceAccessResponseSchema,
  staffWorkspaceSchema,
  staffWorkspacesResponseSchema,
  type ApiError,
  type ApiErrorCode,
  type ApiErrorResponse,
  type AuthErrorCode,
  type InviteStaffRequest,
  type InviteStaffResponse,
  type RevokeStaffResponse,
  type StaffAuthErrorCode,
  type StaffWorkspace,
  type StaffWorkspaceAccessResponse,
  type StaffWorkspacesResponse,
} from './staff-auth';

export {
  createServiceCredentialRequestSchema,
  createServiceCredentialResponseSchema,
  listServiceCredentialsResponseSchema,
  revokeServiceCredentialResponseSchema,
  serviceCredentialSummarySchema,
  websiteAuthErrorCodeSchema,
  websiteScopeSchema,
  type CreateServiceCredentialRequest,
  type CreateServiceCredentialResponse,
  type ListServiceCredentialsResponse,
  type RevokeServiceCredentialResponse,
  type ServiceCredentialSummary,
  type WebsiteAuthErrorCode,
} from './website-auth';

// Request families
export {
  attributionSchema,
  consentVersionSchema,
  createLeadRequestSchema,
  createLeadResponseSchema,
  draftGrantSchema,
  leadContactSchema,
  leadFormSchema,
  leadStatusSchema,
  leadSummarySchema,
  rawAttributionSchema,
  updateLeadRequestSchema,
  updateLeadResponseSchema,
  type Attribution,
  type ConsentVersion,
  type CreateLeadRequest,
  type CreateLeadResponse,
  type DraftGrant,
  type LeadContact,
  type LeadForm,
  type LeadStatus,
  type LeadSummary,
  type RawAttribution,
  type UpdateLeadRequest,
  type UpdateLeadResponse,
} from './leads';

export {
  leadListItemSchema,
  listWorkspaceLeadsQuerySchema,
  listWorkspaceLeadsResponseSchema,
  type LeadListItem,
  type ListWorkspaceLeadsQuery,
  type ListWorkspaceLeadsResponse,
} from './workspace-leads';

export {
  sourceReportDimensionSchema,
  sourceReportGroupSchema,
  sourceReportQuerySchema,
  sourceReportResponseSchema,
  type SourceReportDimension,
  type SourceReportGroup,
  type SourceReportQuery,
  type SourceReportResponse,
} from './reports';

export {
  deleteCustomerDataRequestSchema,
  deleteCustomerDataResponseSchema,
  deletionLedgerStatusSchema,
  type DeleteCustomerDataRequest,
  type DeleteCustomerDataResponse,
  type DeletionLedgerStatus,
} from './deletion';

export {
  chargeComponentSchema,
  createQuoteRequestSchema,
  createQuoteResponseSchema,
  quoteSchema,
  type ChargeComponent,
  type CreateQuoteRequest,
  type CreateQuoteResponse,
  type Quote,
} from './quotes';

export {
  listWebsiteOffersResponseSchema,
  websiteOfferSchema,
  type ListWebsiteOffersResponse,
  type WebsiteOffer,
} from './website-offers';

export {
  orderConsentSchema,
  orderSummarySchema,
  submitOrderRequestSchema,
  submitOrderResponseSchema,
  type OrderConsent,
  type OrderSummary,
  type SubmitOrderRequest,
  type SubmitOrderResponse,
} from './orders';

export {
  amendableContactPatchSchema,
  amendableFormPatchSchema,
  assignableMemberSchema,
  bulkAssignOrderResultSchema,
  bulkAssignOrdersRequestSchema,
  bulkAssignOrdersResponseSchema,
  createOrderChangeRequestRequestSchema,
  createOrderChangeRequestResponseSchema,
  createOrderNoteRequestSchema,
  createOrderReminderRequestSchema,
  createOrderReminderResponseSchema,
  deleteOrderReminderResponseSchema,
  getWorkspaceOrderResponseSchema,
  listAssignableMembersResponseSchema,
  listOrderNotesResponseSchema,
  listWorkspaceOrdersQuerySchema,
  listWorkspaceOrdersResponseSchema,
  orderArchiveFilterSchema,
  orderAmendmentSchema,
  orderAuditEntrySchema,
  orderCapabilitiesSchema,
  orderChangeRequestPatchSchema,
  orderChangeRequestSchema,
  orderChangeRequestStatusSchema,
  orderCustomerSchema,
  orderDetailSchema,
  orderDispatchSchema,
  orderHistoryEntrySchema,
  orderListItemSchema,
  orderNoteSchema,
  orderPaymentSchema,
  orderReminderSchema,
  orderSnapshotSchema,
  patchOrderArchiveRequestSchema,
  patchOrderAssigneeRequestSchema,
  patchWorkspaceOrderRequestSchema,
  patchWorkspaceOrderResponseSchema,
  recordOrderPaymentRequestSchema,
  recordOrderPaymentResponseSchema,
  resolveOrderChangeRequestRequestSchema,
  resolveOrderChangeRequestResponseSchema,
  type AmendableContactPatch,
  type AmendableFormPatch,
  type AssignableMember,
  type BulkAssignOrderResult,
  type BulkAssignOrdersRequest,
  type BulkAssignOrdersResponse,
  type CreateOrderChangeRequestRequest,
  type CreateOrderChangeRequestResponse,
  type CreateOrderNoteRequest,
  type CreateOrderReminderRequest,
  type CreateOrderReminderResponse,
  type DeleteOrderReminderResponse,
  type GetWorkspaceOrderResponse,
  type ListAssignableMembersResponse,
  type ListOrderNotesResponse,
  type ListWorkspaceOrdersQuery,
  type ListWorkspaceOrdersResponse,
  type OrderArchiveFilter,
  type OrderAmendment,
  type OrderAuditEntry,
  type OrderCapabilities,
  type OrderChangeRequest,
  type OrderChangeRequestPatch,
  type OrderChangeRequestStatus,
  type OrderCustomer,
  type OrderDetail,
  type OrderDispatch,
  type OrderHistoryEntry,
  type OrderListItem,
  type OrderNote,
  type OrderPayment,
  type OrderReminder,
  type OrderSnapshot,
  type PatchOrderArchiveRequest,
  type PatchOrderAssigneeRequest,
  type PatchWorkspaceOrderRequest,
  type PatchWorkspaceOrderResponse,
  type RecordOrderPaymentRequest,
  type RecordOrderPaymentResponse,
  type ResolveOrderChangeRequestRequest,
  type ResolveOrderChangeRequestResponse,
} from './workspace-orders';

export {
  createUploadIntentRequestSchema,
  createUploadIntentResponseSchema,
  finalizeUploadRequestSchema,
  finalizeUploadResponseSchema,
  type CreateUploadIntentRequest,
  type CreateUploadIntentResponse,
  type FinalizeUploadRequest,
  type FinalizeUploadResponse,
} from './uploads';

export {
  createDownloadLinkResponseSchema,
  fileStatusSchema,
  fileSummarySchema,
  type CreateDownloadLinkResponse,
  type FileStatus,
  type FileSummary,
} from './files';

export {
  changeCommissionStateRequestSchema,
  changeCommissionStateResponseSchema,
  commissionLineEventSchema,
  commissionLineSchema,
  commissionRuleSchema,
  commissionRuleSnapshotSchema,
  invoiceLineSchema,
  invoiceSchema,
  listPartnersResponseSchema,
  partnerCommissionViewSchema,
  partnerDetailResponseSchema,
  partnerInvoiceRequestSchema,
  partnerInvoiceResponseSchema,
  partnerReferredOrderSchema,
  partnerSchema,
  partnerSummarySchema,
  type ChangeCommissionStateRequest,
  type ChangeCommissionStateResponse,
  type CommissionLine,
  type CommissionLineEvent,
  type CommissionRule,
  type CommissionRuleSnapshot,
  type Invoice,
  type InvoiceLine,
  type ListPartnersResponse,
  type Partner,
  type PartnerCommissionView,
  type PartnerDetailResponse,
  type PartnerInvoiceRequest,
  type PartnerInvoiceResponse,
  type PartnerReferredOrder,
  type PartnerSummary,
} from './partners';

export {
  webhookAckResponseSchema,
  webhookDeliveryRequestSchema,
  webhookProviderSchema,
  type WebhookAckResponse,
  type WebhookDeliveryRequest,
  type WebhookProvider,
} from './webhooks';

export {
  createExportRequestSchema,
  createExportResponseSchema,
  exportJobSchema,
  exportJobStatusSchema,
  exportKindSchema,
  type CreateExportRequest,
  type CreateExportResponse,
  type ExportJob,
  type ExportJobStatus,
  type ExportKind,
} from './exports';

export {
  trackingGrantSchema,
  trackingOtpRequestSchema,
  trackingOtpResponseSchema,
  trackingStatusResponseSchema,
  trackingVerifyRequestSchema,
  trackingVerifyResponseSchema,
  type TrackingGrant,
  type TrackingOtpRequest,
  type TrackingOtpResponse,
  type TrackingStatusResponse,
  type TrackingVerifyRequest,
  type TrackingVerifyResponse,
} from './tracking';

// Endpoint registry, OpenAPI generation, typed client
export {
  endpoints,
  type EndpointAuth,
  type EndpointDef,
  type EndpointHeader,
  type HttpMethod,
} from './endpoints';

export { buildOpenApiDocument, type BuildOpenApiOptions } from './openapi';

export {
  BackendError,
  createBackendClient,
  type BackendClient,
  type BackendClientOptions,
} from './client';
